const UlamList = {
  recipes: [
    {
      id: 1,
      name: 'Adobo',
      image:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Adobo_DSCF4391.jpg/330px-Adobo_DSCF4391.jpg',
      ingredients: [
        '1 kg chicken or pork',
        '1 cup soy sauce',
        '1 cup vinegar',
        '4 cloves garlic, minced',
        '2 bay leaves',
        '1 tsp black peppercorns',
        '1 tsp cooking oil',
      ],
      instructions: [
        'In a large pot, combine soy sauce, vinegar, garlic, bay leaves, and black peppercorns.',
        'Add the chicken or pork and marinate for 30 minutes.',
        'Bring to a boil, then lower the heat and simmer for 30-45 minutes, or until meat is tender.',
        'Heat oil in a separate pan and brown the meat.',
        'Add the browned meat to the simmering sauce and cook for an additional 10 minutes.',
        'Serve hot with steamed rice.',
      ],
    },
    {
      id: 2,
      name: 'Buttered Shrimp',
      image:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Halabos_na_hipon.jpg/360px-Halabos_na_hipon.jpg',
      ingredients: [
        '500g large shrimp, peeled and deveined',
        '2 tablespoons butter',
        '4 cloves garlic, minced',
        '1/4 cup chopped parsley',
        'Salt and pepper to taste',
      ],
      instructions: [
        'In a large pan, melt the butter over medium heat.',
        'Add minced garlic and sauté until fragrant.',
        'Add shrimp and cook until they turn pink and opaque, about 3-4 minutes.',
        'Season with salt and pepper, and sprinkle with chopped parsley.',
        'Serve hot.',
      ],
    },
    {
      id: 3,
      name: 'Tinola',
      image:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Chicken_tinola_with_green_papaya_and_lemongrass.jpg/330px-Chicken_tinola_with_green_papaya_and_lemongrass.jpg',
      ingredients: [
        '1 whole chicken, cut into serving pieces',
        '1 small unripe papaya, cut into wedges',
        '1 bunch spinach (or malunggay leaves)',
        '1 thumb-sized ginger, sliced',
        '4 cloves garlic, minced',
        '1 onion, chopped',
        '2 tablespoons fish sauce',
        '8 cups water',
        'Salt and pepper to taste',
      ],
      instructions: [
        'In a large pot, sauté garlic, ginger, and onion until fragrant.',
        'Add the chicken pieces and cook until they change color.',
        'Pour in the fish sauce and cook for a few minutes.',
        'Add water and bring to a boil, then let it simmer until the chicken is tender.',
        'Add the papaya and cook until it softens.',
        'Stir in the spinach or malunggay leaves and cook until wilted.',
        'Season with salt and pepper to taste.',
        'Serve hot.',
      ],
    },
    {
      id: 4,
      name: 'Binagoongang Baboy',
      image:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/4336Cuisine_and_foods_of_Baliuag%2C_Bulacan_08.jpg/360px-4336Cuisine_and_foods_of_Baliuag%2C_Bulacan_08.jpg',
      ingredients: [
        '500g pork belly, cubed',
        '2 tablespoons shrimp paste (bagoong alamang)',
        '4 cloves garlic, minced',
        '1 onion, chopped',
        '2 tomatoes, chopped',
        '1 eggplant, sliced into rounds',
        '1/2 cup vinegar',
        '1/4 cup sugar',
        'Salt and pepper to taste',
      ],
      instructions: [
        'In a pan, heat some oil and sauté garlic, onion, and tomatoes.',
        'Add the pork belly and cook until it turns brown.',
        'Stir in the shrimp paste, vinegar, and sugar.',
        'Simmer until the pork is tender and the sauce thickens.',
        'Add the eggplant and cook until soft.',
        'Season with salt and pepper to taste.',
        'Serve hot.',
      ],
    },
    {
      id: 5,
      name: 'Sisig',
      image:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Authentic_Kapampangan_Sisig.jpg/360px-Authentic_Kapampangan_Sisig.jpg',
      ingredients: [
        '500g pork face (ears, jowls, and snout)',
        '1/4 cup soy sauce',
        '2-3 pieces green chili peppers (siling haba), minced',
        '1 onion, minced',
        '4 cloves garlic, minced',
        '2 tablespoons mayonnaise',
        '2 tablespoons butter',
        'Calamansi or lemon, for squeezing',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Boil the pork face until tender, then grill or broil until crispy.',
        'Chop the crispy pork into small pieces.',
        'In a pan, heat some oil and sauté garlic and onion until soft.',
        'Add the chopped pork, soy sauce, and green chili peppers.',
        'Cook until the pork is crispy again and the sauce is absorbed.',
        'Stir in mayonnaise, butter, and season with calamansi or lemon, salt, and pepper.',
        'Serve hot.',
      ],
    },
    {
      id: 6,
      name: 'Sinigang na Bangus',
      image:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Fish_sinigang.jpg/330px-Fish_sinigang.jpg',
      ingredients: [
        '1 whole milkfish (bangus), cleaned and sliced into pieces',
        '1 tomato, sliced',
        '1 onion, sliced',
        '2-3 pieces green chili peppers (siling haba)',
        '1 radish, sliced',
        '1 eggplant, sliced into rounds',
        '4-5 cups water',
        '1/4 cup fish sauce (patis)',
        'Tamarind (sampaloc) or sinigang mix (for souring)',
        'Salt and pepper to taste',
      ],
      instructions: [
        'In a pot, bring water to a boil and add the tomato, onion, and radish.',
        'Pour in the fish sauce and tamarind (or sinigang mix) for the sour taste.',
        "Add the milkfish and cook until it's done.",
        'Stir in the green chili peppers, eggplant, and season with salt and pepper.',
        'Serve hot.',
      ],
    },
    {
      id: 7,
      name: 'Sinigang na Pork',
      image:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Sinigang_na_Baboy_DSCF4234.jpg/413px-Sinigang_na_Baboy_DSCF4234.jpg',
      ingredients: [
        '500g pork ribs or belly, cut into serving pieces',
        '1 tomato, sliced',
        '1 onion, sliced',
        '2-3 pieces green chili peppers (siling haba)',
        '1 radish, sliced',
        '1 eggplant, sliced into rounds',
        '4-5 cups water',
        '1/4 cup fish sauce (patis)',
        'Tamarind (sampaloc) or sinigang mix (for souring)',
        'Salt and pepper to taste',
      ],
      instructions: [
        'In a pot, bring water to a boil and add the tomato, onion, and radish.',
        'Pour in the fish sauce and tamarind (or sinigang mix) for the sour taste.',
        "Add the pork ribs or belly and cook until they're tender.",
        'Stir in the green chili peppers, eggplant, and season with salt and pepper.',
        'Serve hot.',
      ],
    },
    {
      id: 8,
      name: 'Pork Steak',
      image:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Bistek_Tagalog_DSCF3899.jpg/330px-Bistek_Tagalog_DSCF3899.jpg',
      ingredients: [
        '500g pork shoulder or loin, sliced into thin pieces',
        '1 onion, sliced',
        '2 cloves garlic, minced',
        '1/4 cup soy sauce',
        '1/4 cup ketchup',
        '1/4 cup water',
        'Salt and pepper to taste',
      ],
      instructions: [
        'In a bowl, marinate pork slices in soy sauce, garlic, and pepper for about 30 minutes.',
        'In a pan, heat some oil and sauté onions until soft.',
        'Add marinated pork slices and cook until brown.',
        'Pour in the ketchup and water, and simmer until the sauce thickens.',
        'Season with salt and pepper to taste.',
        'Serve hot.',
      ],
    },
    {
      id: 9,
      name: 'Adobong Atay',
      image:
        'https://www.lutongbahayrecipe.com/wp-content/uploads/2019/04/lutong-bahay-adobong-atay-ng-manok-1200x1310.jpg',
      ingredients: [
        '500g chicken liver and gizzard',
        '4 cloves garlic, minced',
        '1 onion, chopped',
        '1/4 cup vinegar',
        '1/4 cup soy sauce',
        '1 bay leaf',
        'Salt and pepper to taste',
      ],
      instructions: [
        'In a pan, heat some oil and sauté garlic and onion until soft.',
        'Add chicken liver and gizzard and cook until browned.',
        'Pour in vinegar, soy sauce, and bay leaf, and simmer until the sauce thickens.',
        'Season with salt and pepper to taste.',
        'Serve hot.',
      ],
    },
    {
      id: 10,
      name: 'Lumpiang Shanghai',
      image:
        'https://omnivorescookbook.com/wp-content/uploads/2020/12/201113_Lumpia-Shanghai_550.jpg',
      ingredients: [
        '500g ground pork',
        '1 cup minced carrots',
        '1 cup minced green onions',
        '1 cup minced onion',
        '2 cloves garlic, minced',
        '1 teaspoon salt',
        '1/2 teaspoon pepper',
        '1 pack lumpia wrapper',
        'Cooking oil, for frying',
      ],
      instructions: [
        'In a bowl, mix ground pork, carrots, green onions, onion, garlic, salt, and pepper.',
        'Place a portion of the mixture onto a lumpia wrapper and roll tightly.',
        'Seal the edges with water.',
        'Heat oil in a pan and deep-fry lumpiang shanghai until golden brown and crispy.',
        'Serve hot with a dipping sauce.',
      ],
    },
    {
      id: 11,
      name: 'Kare-Kare',
      image:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Mac_MG_5939.jpg/375px-Mac_MG_5939.jpg',
      ingredients: [
        '500g oxtail, cut into 2-inch pieces',
        '500g tripe, cleaned and sliced',
        '2-3 eggplants, sliced into rounds',
        '1 bunch string beans (sitaw), cut into 2-inch pieces',
        '1 banana flower (puso ng saging), sliced',
        '1/2 cup peanut butter',
        '1/4 cup ground toasted rice (rice flour or ground rice)',
        '4 cloves garlic, minced',
        '1 onion, chopped',
        '2-3 tablespoons shrimp paste (bagoong alamang)',
        'Salt and pepper to taste',
      ],
      instructions: [
        'In a large pot, boil oxtail and tripe in water until tender. Drain and set aside.',
        'In another pot, sauté garlic and onions until fragrant.',
        'Add the boiled oxtail and tripe, and cook for a few minutes.',
        'Pour in the peanut butter and ground toasted rice. Stir well.',
        'Add water to achieve the desired consistency. Simmer until the sauce thickens.',
        'Stir in the vegetables and cook until tender.',
        'Serve with shrimp paste on the side.',
      ],
    },
    {
      id: 12,
      name: 'Pancit Canton',
      image:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Pancit_Ilonggo_Style_-_12110747826.jpg/330px-Pancit_Ilonggo_Style_-_12110747826.jpg',
      ingredients: [
        '250g pancit canton noodles',
        '250g pork, sliced into thin strips',
        '1 cup shrimp, peeled and deveined',
        '1/2 cup chicken, cooked and shredded',
        '1 onion, chopped',
        '3 cloves garlic, minced',
        '1 cup mixed vegetables (carrots, bell peppers, snow peas)',
        '2 tablespoons soy sauce',
        '1/4 cup oyster sauce',
        'Salt and pepper to taste',
      ],
      instructions: [
        'In a large pan, heat oil and sauté garlic and onions until soft.',
        'Add pork and cook until browned.',
        'Stir in shrimp and chicken. Cook until shrimp turns pink.',
        'Add mixed vegetables and cook until tender.',
        'Toss in the pancit canton noodles and season with soy sauce and oyster sauce.',
        'Stir-fry until everything is well combined and noodles are cooked.',
        'Season with salt and pepper to taste.',
      ],
    },
    {
      id: 13,
      name: 'Bicol Express',
      image:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Bicol_Express.jpg/330px-Bicol_Express.jpg',
      ingredients: [
        '500g pork belly, sliced into thin strips',
        '2-3 tablespoons shrimp paste (bagoong alamang)',
        '1 onion, chopped',
        '4 cloves garlic, minced',
        '1-2 cups coconut milk',
        '2-3 pieces green chili peppers (siling haba), sliced',
        'Salt and pepper to taste',
      ],
      instructions: [
        'In a pan, heat some oil and sauté garlic and onions until soft.',
        'Add pork and cook until browned.',
        'Stir in shrimp paste and continue to sauté.',
        'Pour in coconut milk and green chili peppers.',
        'Simmer until the sauce thickens and pork is tender.',
        'Season with salt and pepper to taste.',
      ],
    },
    {
      id: 14,
      name: 'Laing',
      image:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Laing%2C_Bicolano_dish.jpg/345px-Laing%2C_Bicolano_dish.jpg',
      ingredients: [
        '1 cup dried taro leaves (dahon ng gabi)',
        '1/2 cup dried fish (dilis or any dried fish of your choice)',
        '1-2 cups coconut milk',
        '4 cloves garlic, minced',
        '1 onion, chopped',
        '2-3 pieces green chili peppers (siling haba), sliced',
        'Salt and pepper to taste',
      ],
      instructions: [
        'In a pan, sauté garlic and onions until fragrant.',
        'Add dried fish and cook for a few minutes.',
        'Pour in coconut milk and bring to a simmer.',
        'Stir in dried taro leaves and cook until tender and the sauce thickens.',
        'Add green chili peppers and season with salt and pepper to taste.',
      ],
    },
    {
      id: 15,
      name: 'Lechon Kawali',
      image:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Lechon_Kawali.jpg/375px-Lechon_Kawali.jpg',
      ingredients: [
        '500g pork belly, cut into serving pieces',
        '4-5 cups water',
        '2-3 pieces bay leaves',
        'Salt and pepper to taste',
        'Cooking oil, for frying',
      ],
      instructions: [
        'In a pot, boil pork belly in water with bay leaves until tender. Drain and let it cool.',
        'Deep-fry the pork pieces in hot oil until they become crispy and golden brown.',
        'Season with salt and pepper to taste.',
        'Serve hot and crispy as a viand or pulutan (appetizer).',
      ],
    },
    {
      id: 16,
      name: 'Kinalabasang Hipon',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlSDdIvsA4TWVyPVE0A7IaImv95b9as3ciLjRFcV03rNU3tReCpwfhvZXvZm2jf0riSLM&usqp=CAU',
      ingredients: [
        '500g large shrimp, peeled and deveined',
        '2 cups squash (kalabasa), cubed',
        '1 cup string beans (sitaw), cut into 2-inch pieces',
        '1 cup malunggay leaves (or spinach)',
        '2 cloves garlic, minced',
        '1 onion, chopped',
        '1-2 cups coconut milk',
        '2-3 pieces green chili peppers (siling haba)',
        'Salt and pepper to taste',
      ],
      instructions: [
        'In a pot, sauté garlic and onions until fragrant.',
        'Add squash and string beans, and cook for a few minutes.',
        'Pour in coconut milk and bring to a simmer.',
        'Add shrimp and green chili peppers. Cook until shrimp turns pink.',
        'Stir in malunggay leaves (or spinach) and season with salt and pepper.',
        'Serve hot.',
      ],
    },
    {
      id: 17,
      name: 'Kilawin',
      image:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Kilawen_Kambing.jpg/375px-Kilawen_Kambing.jpg',
      ingredients: [
        '500g fresh fish or seafood (such as tanigue, tuna, or shrimp)',
        '1 onion, chopped',
        '2-3 pieces green chili peppers (siling haba), minced',
        '1/4 cup vinegar',
        '1/4 cup calamansi or lemon juice',
        '1 thumb-sized ginger, minced',
        'Salt and pepper to taste',
      ],
      instructions: [
        'In a bowl, combine fish or seafood, vinegar, and calamansi or lemon juice. Let it marinate for a few minutes.',
        'Add onion, green chili peppers, and ginger. Mix well.',
        'Season with salt and pepper to taste.',
        'Serve chilled as a refreshing appetizer.',
      ],
    },
    {
      id: 18,
      name: 'Ginataang Langka',
      image:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Ginataang_langka_with_shrimp_and_calamari.jpg/330px-Ginataang_langka_with_shrimp_and_calamari.jpg',
      ingredients: [
        '2 cups young jackfruit (langka), sliced',
        '1 cup shrimp, peeled and deveined',
        '1 cup malunggay leaves (or spinach)',
        '2-3 pieces green chili peppers (siling haba), sliced',
        '2-3 cloves garlic, minced',
        '1 onion, chopped',
        '1-2 cups coconut milk',
        'Salt and pepper to taste',
      ],
      instructions: [
        'In a pan, sauté garlic and onions until fragrant.',
        'Add shrimp and cook until they turn pink.',
        'Stir in young jackfruit and cook for a few minutes.',
        'Pour in coconut milk and green chili peppers. Simmer until the sauce thickens.',
        'Stir in malunggay leaves (or spinach) and season with salt and pepper.',
        'Serve hot.',
      ],
    },
    {
      id: 19,
      name: 'Pakbet',
      image:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Pinakbet3.jpg/330px-Pinakbet3.jpg',
      ingredients: [
        '1 cup sliced eggplant',
        '1 cup sliced okra',
        '1 cup sliced squash',
        '1 cup string beans (sitaw), cut into 2-inch pieces',
        '1/2 cup bitter melon (ampalaya), sliced',
        '1/2 cup shrimp paste (bagoong alamang)',
        '2-3 cloves garlic, minced',
        '1 onion, chopped',
        '2-3 pieces tomatoes, chopped',
        '2 tablespoons fish sauce (patis)',
        'Salt and pepper to taste',
      ],
      instructions: [
        'In a pan, sauté garlic and onions until fragrant.',
        'Add tomatoes and cook until they soften.',
        'Stir in eggplant, okra, squash, and string beans. Cook for a few minutes.',
        'Add shrimp paste and fish sauce. Mix well.',
        'Season with salt and pepper to taste.',
        'Serve hot as a vegetable side dish.',
      ],
    },
    {
      id: 20,
      name: 'Inihaw na Liempo',
      image:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Sinugba_na_baboy_%28inihaw_na_baboy%29_with_dipping_sauce%2C_Philippines.jpg/225px-Sinugba_na_baboy_%28inihaw_na_baboy%29_with_dipping_sauce%2C_Philippines.jpg',
      ingredients: [
        '500g pork belly',
        '4-5 cloves garlic, minced',
        '1/4 cup soy sauce',
        '1/4 cup vinegar',
        '1 teaspoon brown sugar',
        'Salt and pepper to taste',
      ],
      instructions: [
        'In a bowl, marinate pork belly with garlic, soy sauce, vinegar, brown sugar, salt, and pepper for about 30 minutes.',
        "Grill the marinated pork over charcoal or on a grill until it's cooked and has a nice char.",
        'Slice and serve hot as a grilled dish.',
      ],
    },
    {
      id: 21,
      name: 'La Paz Batchoy',
      image:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/LaPazBatchoy.jpg/368px-LaPazBatchoy.jpg',
      ingredients: [
        '250g miki noodles',
        '250g pork, sliced into thin strips',
        '1/2 cup chicken liver, sliced',
        '4-5 cloves garlic, minced',
        '1 onion, chopped',
        '4 cups pork broth',
        '2-3 tablespoons fish sauce (patis)',
        '1 boiled egg, sliced',
        'Chicharron (pork cracklings) for topping',
        'Spring onions, chopped, for garnish',
      ],
      instructions: [
        'In a pot, sauté garlic and onions until fragrant.',
        'Add pork and chicken liver. Cook until browned.',
        'Pour in pork broth and bring to a boil.',
        'Add miki noodles and cook until tender.',
        'Season with fish sauce and garnish with boiled egg, chicharron, and spring onions.',
        'Serve hot.',
      ],
    },
    {
      id: 22,
      name: 'Kinilaw na Isda',
      image:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Kagay-anon_Kinilaw.jpg/405px-Kagay-anon_Kinilaw.jpg',
      ingredients: [
        '500g fresh fish (tanigue, tuna, or any white fish), cubed',
        '1 cucumber, peeled and sliced',
        '1 onion, chopped',
        '2-3 pieces green chili peppers (siling haba), minced',
        '1/4 cup vinegar',
        '1/4 cup calamansi or lemon juice',
        'Salt and pepper to taste',
      ],
      instructions: [
        'In a bowl, combine fresh fish, vinegar, and calamansi or lemon juice. Let it marinate for a few minutes.',
        'Add onion, cucumber, and green chili peppers. Mix well.',
        'Season with salt and pepper to taste.',
        'Serve chilled as a refreshing appetizer.',
      ],
    },
    {
      id: 23,
      name: 'Sinampalukang Manok',
      image:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Sinampalukan.jpg/360px-Sinampalukan.jpg',
      ingredients: [
        '1 whole chicken, cut into serving pieces',
        '1 bunch young tamarind leaves (dahon ng sampalok)',
        '2-3 cloves garlic, minced',
        '1 onion, chopped',
        '2-3 pieces green chili peppers (siling haba)',
        '2 tablespoons fish sauce (patis)',
        'Salt and pepper to taste',
      ],
      instructions: [
        'In a pot, sauté garlic and onions until fragrant.',
        'Add chicken pieces and cook until they change color.',
        'Pour in water and bring to a boil.',
        'Add young tamarind leaves (dahon ng sampalok) and green chili peppers. Simmer until the chicken is tender.',
        'Season with fish sauce, salt, and pepper to taste.',
        'Serve hot.',
      ],
    },

    {
      id: 24,
      name: 'Paksiw na Bangus',
      image:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/JfMalhacan9018MeycauayanCityfvf_06.JPG/345px-JfMalhacan9018MeycauayanCityfvf_06.JPG',
      ingredients: [
        '2 whole milkfish (bangus), cleaned and sliced',
        '1/4 cup vinegar',
        '2-3 pieces green chili peppers (siling haba)',
        '1 onion, chopped',
        '3 cloves garlic, minced',
        '1/4 cup water',
        'Salt and pepper to taste',
      ],
      instructions: [
        'In a pot, combine milkfish, vinegar, water, garlic, onion, and green chili peppers.',
        'Simmer until the fish is cooked and the sauce thickens.',
        'Season with salt and pepper to taste.',
        'Serve hot with steamed rice.',
      ],
    },
    {
      id: 25,
      name: 'Tortang Talong',
      image:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/EGGPLANT_TORTA.jpg/375px-EGGPLANT_TORTA.jpg',
      ingredients: [
        '2-3 eggplants (talong)',
        '2-3 eggs, beaten',
        '1/4 cup ground pork',
        '1 onion, chopped',
        '3 cloves garlic, minced',
        'Salt and pepper to taste',
        'Cooking oil for frying',
      ],
      instructions: [
        'Grill the eggplants until the skin is charred and the flesh is soft. Remove the skin and flatten the eggplants.',
        'In a pan, sauté garlic and onions until soft.',
        'Dip each eggplant in beaten eggs, add a spoonful of ground pork, and fry until golden brown.',
        'Season with salt and pepper to taste.',
        'Serve hot.',
      ],
    },
  ],
};
export default UlamList;
